sudo: false
dist: xenial  # required for Python >= 3.7
language: python
matrix:
  include:
    - python: 3.6
      env:
         - TOX_ENV=travis
    - python: 3.7
      env:
         - TOX_ENV=travis
    - python: 3.8-dev
      env:
         - TOX_ENV=travis
install:
 - pip install codecov
 - pip install tox-travis
script:
 - tox -e $TOX_ENV
after_success:
 - codecov
