sudo: false
language: python
python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
env:
 - TOX_ENV=flake8
 - TOX_ENV=isort
 - TOX_ENV=pydocstyle
 - TOX_ENV=py36
install:
 - pip install codecov
 - pip install tox-travis
script:
 - tox -e $TOX_ENV
after_success:
 - codecov
